# Generated by minicc
# Target: RISC-V 32

    .text
    .globl _start
_start:
    call main
    # exit(a0) - 返回值已在 a0 中
    li a7, 93
    ecall

    .globl add
add:
    addi sp, sp, -64
    sw ra, 60(sp)
    sw s0, 56(sp)
    addi s0, sp, 64
    sw a0, -12(s0)
    sw a1, -16(s0)
    lw a0, -16(s0)
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, -12(s0)
    lw a1, 0(sp)
    addi sp, sp, 4
    add a0, a0, a1
    j .Lret0
.Lret0:
    lw ra, 60(sp)
    lw s0, 56(sp)
    addi sp, sp, 64
    ret

    .globl square
square:
    addi sp, sp, -64
    sw ra, 60(sp)
    sw s0, 56(sp)
    addi s0, sp, 64
    sw a0, -12(s0)
    lw a0, -12(s0)
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, -12(s0)
    lw a1, 0(sp)
    addi sp, sp, 4
    mul a0, a0, a1
    j .Lret1
.Lret1:
    lw ra, 60(sp)
    lw s0, 56(sp)
    addi sp, sp, 64
    ret

    .globl main
main:
    addi sp, sp, -64
    sw ra, 60(sp)
    sw s0, 56(sp)
    addi s0, sp, 64
    li a0, 4
    addi sp, sp, -4
    sw a0, 0(sp)
    li a0, 3
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, 0(sp)
    lw a1, 4(sp)
    addi sp, sp, 8
    call add
    sw a0, -12(s0)
    li a0, 5
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, 0(sp)
    addi sp, sp, 4
    call square
    sw a0, -16(s0)
    lw a0, -16(s0)
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, -12(s0)
    addi sp, sp, -4
    sw a0, 0(sp)
    lw a0, 0(sp)
    lw a1, 4(sp)
    addi sp, sp, 8
    call add
    j .Lret2
.Lret2:
    lw ra, 60(sp)
    lw s0, 56(sp)
    addi sp, sp, 64
    ret
