source "https://rubygems.org/"

gem "jekyll", "~> 4.3"
gem "minimal-mistakes-jekyll", "~> 4.26"

group :jekyll_plugins do
  gem "jekyll-sitemap"
  gem "jekyll-relative-links"
  gem "jekyll-optional-front-matter"
  gem "jekyll-titles-from-headings"
  gem "jekyll-redirect-from"
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
end
