/*
 * minicc - A mini C compiler targeting RISC-V 32
 * Step 1: 基础框架 - 命令行处理和文件 I/O
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#define VERSION "0.1"

/* 编译器配置 */
typedef struct {
    char *input_file;   /* 输入源文件 */
    char *output_file;  /* 输出汇编文件 */
    int verbose;        /* 详细输出模式 */
} Config;

/* 全局配置 */
static Config config = {0};

/* 打印使用说明 */
void print_usage(const char *prog_name) {
    fprintf(stderr, "Usage: %s [options] <input.c>\n", prog_name);
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -o <file>    指定输出文件 (默认: out.s)\n");
    fprintf(stderr, "  -v           详细输出模式\n");
    fprintf(stderr, "  -h           显示帮助信息\n");
    fprintf(stderr, "  --version    显示版本信息\n");
}

/* 解析命令行参数 */
int parse_args(int argc, char **argv) {
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-h") == 0 || strcmp(argv[i], "--help") == 0) {
            print_usage(argv[0]);
            exit(0);
        }
        if (strcmp(argv[i], "--version") == 0) {
            printf("minicc version %s\n", VERSION);
            exit(0);
        }
        if (strcmp(argv[i], "-v") == 0) {
            config.verbose = 1;
            continue;
        }
        if (strcmp(argv[i], "-o") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "错误: -o 需要指定输出文件名\n");
                return -1;
            }
            config.output_file = argv[++i];
            continue;
        }
        /* 假定是输入文件 */
        if (argv[i][0] == '-') {
            fprintf(stderr, "错误: 未知选项 '%s'\n", argv[i]);
            return -1;
        }
        if (config.input_file) {
            fprintf(stderr, "错误: 只能指定一个输入文件\n");
            return -1;
        }
        config.input_file = argv[i];
    }

    if (!config.input_file) {
        fprintf(stderr, "错误: 没有指定输入文件\n");
        return -1;
    }
    if (!config.output_file) {
        config.output_file = "out.s";
    }

    return 0;
}

/* 读取整个文件内容 */
char *read_file(const char *filename) {
    FILE *fp = fopen(filename, "r");
    if (!fp) {
        fprintf(stderr, "错误: 无法打开文件 '%s': %s\n",
                filename, strerror(errno));
        return NULL;
    }

    /* 获取文件大小 */
    fseek(fp, 0, SEEK_END);
    long size = ftell(fp);
    fseek(fp, 0, SEEK_SET);

    /* 分配内存并读取 */
    char *buf = malloc(size + 1);
    if (!buf) {
        fprintf(stderr, "错误: 内存分配失败\n");
        fclose(fp);
        return NULL;
    }

    size_t read_size = fread(buf, 1, size, fp);
    buf[read_size] = '\0';
    fclose(fp);

    if (config.verbose) {
        printf("[INFO] 读取文件 '%s' (%ld 字节)\n", filename, size);
    }

    return buf;
}

/* 生成 RISC-V 汇编代码 (Step 1: 仅生成框架) */
int generate_asm(const char *source, FILE *out) {
    if (config.verbose) {
        printf("[INFO] 生成 RISC-V 汇编代码...\n");
    }

    /* Step 1: 生成一个简单的 hello world 汇编框架 */
    fprintf(out, "# Generated by minicc %s\n", VERSION);
    fprintf(out, "# Target: RISC-V 32\n\n");

    fprintf(out, "    .section .data\n");
    fprintf(out, "msg:\n");
    fprintf(out, "    .string \"Hello, World!\\n\"\n");
    fprintf(out, "    .set msg_len, . - msg\n\n");

    fprintf(out, "    .section .text\n");
    fprintf(out, "    .globl _start\n\n");

    fprintf(out, "_start:\n");
    fprintf(out, "    # write(1, msg, msg_len)\n");
    fprintf(out, "    li a7, 64          # syscall: write\n");
    fprintf(out, "    li a0, 1           # fd: stdout\n");
    fprintf(out, "    la a1, msg         # buf: message\n");
    fprintf(out, "    li a2, msg_len     # count: length\n");
    fprintf(out, "    ecall\n\n");

    fprintf(out, "    # exit(0)\n");
    fprintf(out, "    li a7, 93          # syscall: exit\n");
    fprintf(out, "    li a0, 0           # status: 0\n");
    fprintf(out, "    ecall\n");

    return 0;
}

int main(int argc, char **argv) {
    /* 解析命令行参数 */
    if (parse_args(argc, argv) != 0) {
        print_usage(argv[0]);
        return 1;
    }

    if (config.verbose) {
        printf("[INFO] minicc %s\n", VERSION);
        printf("[INFO] 输入: %s\n", config.input_file);
        printf("[INFO] 输出: %s\n", config.output_file);
    }

    /* 读取源文件 */
    char *source = read_file(config.input_file);
    if (!source) {
        return 1;
    }

    /* 打开输出文件 */
    FILE *out = fopen(config.output_file, "w");
    if (!out) {
        fprintf(stderr, "错误: 无法创建输出文件 '%s': %s\n",
                config.output_file, strerror(errno));
        free(source);
        return 1;
    }

    /* 生成汇编代码 */
    int result = generate_asm(source, out);

    fclose(out);
    free(source);

    if (result == 0 && config.verbose) {
        printf("[INFO] 编译完成: %s\n", config.output_file);
    }

    return result;
}
